name: Deploy to heroku

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and upload
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.EMAIL }}
        heroku_api_key: ${{ secrets.API_KEY}}
        heroku_app_name: ${{ secrets.APP_NAME}}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
